[project]
name = "youtube-notify"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14, <4.0"
license-files = ["LICENSE"]
authors = [
    { name = "Jack Stockley", email = "jack@jstockley.com"}
]
keywords = ["starter", "template", "python"]
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "python-dotenv==1.2.2",
]
[project.urls]
Homepage = "https://github.com/jnstockley/youtube-notify"
Repository = "https://github.com/jnstockley/youtube-notify.git"
Issues = "https://github.com/jnstockley/youtube-notify/issues"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pytest-cov>=6.0.0",
    "ruff>=0.13.2",
]
